language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - devtools

env:
  global:
    - NETLIFY_SITE_ID=ba0a8045-469c-4ea3-bd7c-9aedab996798

before_install:
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

before_cache:
- nvm install stable
- npm install netlify-cli -g

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
